version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/InvBase/allstatic

  web:
    image: hastrodis/test:latest
    command: sh -c "/InvBase/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public:/InvBase/allstatic

  db:
    image: postgres:11-alpine
    restart: always
    env_file:
    - .env
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/dumps:/dumps

  search:
    image: elasticsearch:7.12.1
    container_name: search
    env_file:
    - .env
    environment:
      - node.name=search
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=search
      #- discovery.type:"single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
