version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/code/public

  web:
    image: hastrodis/test:latest
    command: sh -c "/InvBase/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public:/code/public

  db:
    image: postgres:11-alpine
    restart: always
    env_file:
    - .env
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/dumps:/dumps

  search:
    image: elasticsearch:7.12.1
    restart: always
    ports:
      - 9200:9200
    environment:
      - xpack.ml.enabled=false
    volumes:
      - ./elasticsearch/data:/data
    