# Generated by Django 3.0.3 on 2020-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0003_auto_20200512_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techn',
            name='Prim',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
