# Generated by Django 2.2.15 on 2020-09-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0004_auto_20200512_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techn',
            name='DataUtil',
        ),
    ]
