# Generated by Django 3.1.5 on 2021-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0005_remove_techn_datautil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techn',
            name='InvNomer',
            field=models.TextField(max_length=50),
        ),
    ]
