# Generated by Django 3.1.5 on 2021-01-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0006_auto_20210108_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techn',
            name='InvNomer',
            field=models.CharField(max_length=50),
        ),
    ]
