# Generated by Django 3.1.5 on 2021-01-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0009_auto_20210109_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='IDuser',
            new_name='user',
        ),
    ]
