# Generated by Django 3.1.5 on 2021-01-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SaveBase', '0011_auto_20210109_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='IDSotrud',
        ),
        migrations.AddField(
            model_name='history',
            name='FIOPod',
            field=models.CharField(default=0, max_length=150, verbose_name='Подотчетное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techn',
            name='IDUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
