# Generated by Django 3.1.5 on 2021-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveBase', '0012_auto_20210109_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_podot',
            field=models.BooleanField(default=True),
        ),
    ]
